#!/usr/bin/env python


def main():
    """
    ALeRCE Late Classifier.
    """
    try:
        from late_classifier.management import cli
    except ImportError as e:
        raise ImportError from e
    cli()


if __name__ == '__main__':
    main()
